import os
import json
import asyncio
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import Response
from fastapi.middleware.cors import CORSMiddleware
from aiokafka import AIOKafkaConsumer
import httpx
import xml.etree.ElementTree as ET
from app.database import engine
from app.models import Base
from app.routes.history import router as history_router
from app.routes.cases import router as cases_router

KAFKA_BROKERS = os.getenv("KAFKA_BROKERS", "localhost:9092")
LLM_SERVICE_URL = os.getenv("LLM_SERVICE_URL", "http://localhost:8004")
GRAPH_SERVICE_URL = os.getenv("GRAPH_SERVICE_URL", "http://localhost:8002")

app = FastAPI(title="Dashboard API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

clients = set()

@app.on_event("startup")
async def startup_event():
    # Ensure DB tables exist (uses same DATABASE_URL as risk-engine when configured)
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
            print("Dashboard API DB tables ensured")
    except Exception as e:
        print(f"Warning: could not create DB tables for dashboard-api: {e}")

    app.include_router(history_router)
    app.include_router(cases_router)

    asyncio.create_task(consume_risk_scores())

async def consume_risk_scores():
    while True:
        try:
            consumer = AIOKafkaConsumer(
                "risk-scores",
                bootstrap_servers=KAFKA_BROKERS,
                value_deserializer=lambda v: json.loads(v.decode('utf-8')),
                auto_offset_reset="latest"
            )
            await consumer.start()
            try:
                async for msg in consumer:
                    payload = msg.value
                    for ws in list(clients):
                        try:
                            await ws.send_json(payload)
                        except Exception:
                            if ws in clients:
                                clients.remove(ws)
            finally:
                await consumer.stop()
        except Exception as e:
            print(f"Failed to start dashboard kafka consumer: {e}. Retrying in 3s...")
            await asyncio.sleep(3)

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    clients.add(websocket)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        clients.remove(websocket)

@app.post("/api/explain")
async def explain_transaction(payload: dict):
    # Proxy to llm-service
    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(f"{LLM_SERVICE_URL}/explain", json=payload, timeout=30.0)
            return resp.json()
        except Exception as e:
            return {"error": str(e), "explanation": "Unable to reach LLM service."}

@app.get("/api/graph/{account_id}")
async def get_graph(account_id: str):
    # Proxy to graph-service
    async with httpx.AsyncClient() as client:
        try:
            resp = await client.get(f"{GRAPH_SERVICE_URL}/graph/{account_id}", timeout=10.0)
            return resp.json()
        except Exception as e:
            return {"error": str(e), "nodes": [], "edges": []}

@app.get("/api/str/{case_id}")
async def generate_str_xml(case_id: str):
    root = ET.Element("SuspiciousTransactionReport")
    fiu_header = ET.SubElement(root, "ReportHeader")
    ET.SubElement(fiu_header, "ReportFormatCode").text = "ARF1.0"
    ET.SubElement(fiu_header, "ReportType").text = "SuspiciousTransaction"
    
    case_details = ET.SubElement(root, "CaseDetails")
    ET.SubElement(case_details, "CaseID").text = case_id
    ET.SubElement(case_details, "Status").text = "N"
    ET.SubElement(case_details, "SuspicionDetails").text = "Generated by FundGuard Risk Engine. Awaiting analyst review."
    
    # Normally we would fetch the case details from the database here
    
    xml_str = ET.tostring(root, encoding="utf-8", xml_declaration=True)
    return Response(
        content=xml_str,
        media_type="application/xml",
        headers={"Content-Disposition": f'attachment; filename="STR_{case_id}.xml"'}
    )
